### PR TITLE
allow use of json option

### LINKED ISSUE #7: JSON option throws warning
The `json` option was removed in commit 151e37abb84ebcbcbb4d2cc780b89fa98f23b1b1 , but only from the `README.md` and `action.yml` files

This means that JSON output is still possible, for example using:
```
      - uses: CycloneDX/gh-node-module-generatebom@v1.0.2
        with:
          json: true
```
 and the JSON output is obtained after displaying a warning: `Warning: Unexpected input(s) 'json', valid inputs are ['path', 'output']`

Could we reinstate the use of `json` option and get rid of the warning from `action.yml`? This would be my preferred outcome rather than removing `json` option altogether

### PR DESCRIPTION
**Pull request by jgadsden**
This reinstates the json option and provides an example step for it

closes #7

### CODE REVIEW

**Comment by jkowalleck** [comment]
you added an option that is not used at any active code.
did you forget something? 

put it to DRAFT state until this changes.

**Comment by jgadsden** [comment]
@jkowalleck I did not sign off the commit message, do you want me to do this?

**Comment by jkowalleck** [comment]
> @jkowalleck I did not sign off the commit message, do you want me to do this?

yes, please. 
Instructions are shown here: https://github.com/CycloneDX/gh-node-module-generatebom/pull/9/checks?check_run_id=13295033480

**Comment by jgadsden** [comment]
Closing this because it is not required as explained by @jkowalleck :

generating json output is controlled by putting a `.json` file as the output.
nothing more to it. 
see the docs: https://www.npmjs.com/package/@cyclonedx/bom/v/3.10.6
_Originally posted by @jkowalleck in https://github.com/CycloneDX/gh-node-module-generatebom/issues/7#issuecomment-1537463475_

**Pull request closed without merging**
